# DAT210x - Programming with Python for DS

## Module2 - Lab3

In [1]:
# Import and alias Pandas
import pandas as pd

Often, you will want to load a dataset that is missing explicit header labels. You won't know if your data lacks headers or not unless you load it up and examine the headers to see if they make sense. Pandas by default reads in the first row of data as the header. If that isn't the case for your specific data set, you will lose your first data row. Be careful!

Load up the `Servo.data` dataset. Examine the headers, and adjust them as necessary, if need be.

In [5]:
df=pd.read_csv('servo.data', header=None, names=['motor', 'screw', 'pgain', 'vgain', 'class'])
df

    motor screw  pgain  vgain     class
0       E     E      5      4  0.281251
1       B     D      6      5  0.506252
2       D     D      4      3  0.356251
3       B     A      3      2  5.500033
4       D     B      6      5  0.356251
5       E     C      4      3  0.806255
6       C     A      3      2  5.100014
7       A     A      3      2  5.700042
8       C     A      6      5  0.768754
9       D     A      4      1  1.031254
10      B     E      6      5  0.468752
11      E     C      5      4  0.393752
12      B     C      4      1  0.281251
13      E     C      3      1  1.100000
14      C     C      5      4  0.506252
15      E     B      3      2  1.899990
16      D     C      3      1  0.900001
17      B     C      5      4  0.468752
18      B     B      5      4  0.543753
19      C     E      4      2  0.206250
20      E     D      4      3  0.918755
21      A     D      4      3  1.106248
22      B     C      6      5  0.468752
23      A     C      4      2  0.581253
24      A     B      6      5  0.581253
25      E     C      6      5  0.393752
26      A     A      3      1  5.300024
27      A     E      4      2  0.468752
28      C     D      3      2  1.899990
29      B     B      3      2  4.299977
..    ...   ...    ...    ...       ...
137     A     C      5      4  0.506252
138     B     E      4      1  0.206250
139     C     B      3      1  3.899964
140     E     E      4      2  0.506252
141     B     E      4      3  1.106248
142     A     E      3      1  3.899964
143     A     B      4      2  0.806255
144     A     C      3      1  3.899964
145     E     C      3      2  1.499995
146     B     A      3      1  5.100014
147     D     D      3      2  1.499995
148     A     C      3      2  4.699995
149     E     A      4      1  0.881255
150     B     A      5      4  0.806255
151     E     E      3      1  0.700001
152     D     E      3      2  0.900001
153     E     B      3      1  1.499995
154     A     D      4      1  0.243751
155     A     D      3      1  4.099967
156     E     B      4      3  0.993756
157     A     B      3      1  4.699995
158     D     B      4      3  0.581253
159     A     A      5      4  0.806255
160     D     A      3      2  2.699979
161     C     E      6      5  0.468752
162     B     C      3      2  4.499986
163     B     E      3      1  3.699967
164     C     D      4      3  0.956256
165     A     B      3      2  4.499986
166     A     A      6      5  0.806255

[167 rows x 5 columns]

Let's try experimenting with some slicing. Create a slice that contains all entries that have a vgain equal to 5. Then print the length of (# of samples in) that slice:

In [26]:
df[df['vgain']==5].describe()

       pgain  vgain      class
count   22.0   22.0  22.000000
mean     6.0    5.0   0.511366
std      0.0    0.0   0.138050
min      6.0    5.0   0.281251
25%      6.0    5.0   0.440627
50%      6.0    5.0   0.506252
75%      6.0    5.0   0.543753
max      6.0    5.0   0.806255

Create a slice that contains all entries having a motor equal to E and screw equal to E. Then print the length of (# of samples in) that slice:

In [21]:
a=df[(df['motor'] == "E") & (df['screw'] == "E")]
len(a)

6

Create a slice that contains all entries having a pgain equal to 4. Use one of the various methods of finding the mean vgain value for the samples in that slice. Once you've found it, print it:

In [24]:
df[(df['pgain'] == 4)].describe()

       pgain      vgain      class
count   66.0  66.000000  66.000000
mean     4.0   2.060606   0.673298
std      0.0   0.820484   0.314105
min      4.0   1.000000   0.131250
25%      4.0   1.000000   0.365627
50%      4.0   2.000000   0.712504
75%      4.0   3.000000   0.956256
max      4.0   3.000000   1.218740

Here's a bonus activity for you. See what happens when you display the `.dtypes` property of your dataframe!

In [25]:
df.dtypes

motor     object
screw     object
pgain      int64
vgain      int64
class    float64
dtype: object